spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      force-response: true